name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@ca4f81e33224edb4105e88f8962acdd07073221d # renovate: tag=latest
      - run: echo "Hello world!"
